Ns rse/141 missing json
claritychallenge/clarity pull request #143
Opened 2022-12-02 16:10 UTC by ns-rse

2022-12-03 12:57 UTC, jonbarker68 requested changes
This all looks good but please remove the exp/exp/si.csv and exp/exp/unproc_si.csv. These files are already in exp/. I think there is actually a config error in the recipe that ends up putting results in exp/exp rather than exp/. but that's a separate issue and not a big problem)

As an aside: I note that the results in exp/exp/ don't match the existing one's exp/ . This worried me so I have rerun to check and the ones in exp/ appear correct.  So, yes, please delete the CEC2/baseline/exp/exp files.

2022-12-03 12:57 UTC, jonbarker68 commented on recipes/cec2/baseline/exp/exp/si.csv
> +scene,listener,haspi
This file exp/exp/si.csv shouldn't be included, there is already an exp/si.csv (worrying though because the numbers are different)

2022-12-03 12:57 UTC, jonbarker68 commented on recipes/cec2/baseline/exp/exp/si_unproc.csv
> +scene,listener,haspi
This file exp/exp/si_unproc.csv shouldn't be included, there is already a exp/si_unproc.csv (worrying though because the numbers are different)

2022-12-05 11:00 UTC, jonbarker68 approved these changes
Thanks. This all looks good.

2022-12-05 11:08 UTC, ns-rse commented
Thanks for the sanity check @jonbarker68 I did wonder why there were two similar files but they're only there on my local branch which is mildly confusing as I branched anew from `main`.

Anyway, I'll merge this release `v0.2.1` and then sort out a `v0.1.1` release too.

2022-12-05 11:08 UTC, merged